label:          Classification
data_directory: /grand/datascience/cadams/datasets/DUNE/pixsim_small/
train_file:     train.h5
test_file:      none
val_file:       test.h5
access_mode:    random_blocks
dimension:      3
